manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson/
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
    - name: urob
      url-base: https://github.com/urob
    - name: mjmjm0101
      url-base: https://github.com/willem640

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: cirque-input-module
      remote: geeksville
      revision: toucan
    - name: zmk-rgbled-widget
      remote: caksoylar
    - name: zmk-auto-layer
      remote: urob
    - name: zmk-input-processor-scroll-inertia
      remote: mjmjm0101
      revision: main # AI-generated code, probably a source of bugs in the future
  self:
    path: config
